### ISSUE TITLE
Enable comments

### ISSUE THREAD

**Issue by rnicholus** [Widen/widen.github.io#21]
After some reflection, I think this is an important feature, and would be very easy to add. I recall hearing twitter as an alternative to enabling in-post comments, but that limits commenters to 140 characters, and it's a bit awkward to comment on a specific article outside of the article. Disqus is the most common solution.

**Comment by dbeg** [comment]
:+1: disqus

**Comment by dbeg** [comment]
@rnicholus comments are not appearing on http://engineering.widen.com/blog/2015/08/27/AWS-Lambda-Runtime-Configuration/

**Comment by rnicholus** [comment]
@dbeg This is intentional. @feltnerm Wanted comments off for his post. Notice the `comments: false` frontmatter added to his post in c64fd46.

**Comment by feltnerm** [comment]
I think I'd prefer people writing me an email or their own blog post rather than just submitting a comment... i'm weird tho

**Comment by dbeg** [comment]
Seems a bit odd to have a disparity between posts instead of a site-wide feature.

**Comment by rnicholus** [comment]
I think it's reasonable to expect that some posters may not want random people commenting on their writing.
