### ISSUE TITLE
Required Tasks to Ship

### ISSUE THREAD

**Issue by rnicholus** [Widen/widen.github.io#5]
If we want this to be completed, a set of small tasks required to make it happen will be needed. @feltnerm @dbeg what are the remaining items to be completed?

**Comment by feltnerm** [comment]
Here's the current list.

- [ ] Document instructions for adding posts, pages
- [ ] Create script to assist creating new post (i.e., `./create-post {title}`)
- [ ] Create script to assist in deployment (i.e., Travis-CI could deploy to `gh-pages` if conditions are met or something)
- [ ] Style site to match Widen "brand" (doesn't need to be 1:1, but shouldn't look like another company)
- [ ] RSS feed
- [ ] Categories / tags support

**Pages**:

- [ ] Author page - information about each other + picture + links to social media
    - [ ] template
    - [ ] author pages copy text
    - [ ] author page styling
- [ ] About page - what we're about
    - [ ] about page copy text
    - [ ] about page styling
- [ ] Software page - list of our open-source offerings w/ short descriptions
    - [ ] software page template
    - [ ] software page copy
    - [ ] software page styling
- [ ] Post list page - list of blog posts
    - [ ] post list page template (needs some <3)
    - [ ] post list page styling
- [ ] Post page - a single blog post page
    - [ ] post page template
    - [ ] post page styling

**Partials**:

- [ ] Header
    - [ ] Style
    - [ ] Links
- [ ] Footer
    - [ ] Style
    - [ ] Links

I'll keep it updated if anyone sees anything I'm missing:

**Comment by rnicholus** [comment]
I know marketing is currently using Compendium for their blogging platform. They're not happy with it and are actively looking for a replacement. Regardless, Compendium and most other blogging/authoring platforms already allows us to satisfy all of the requirements here. We want to blog about technology, but we are pretty limited on time. Maybe we should spend that time blogging instead of wiring together our own a blogging platform. Perhaps coordinating with marketing to find a suitable platform for both dev and marketing is an avenue to explore. If both marketing and dev are using the same platform, it will be easier to have a consistent experience and L&F between the two.

**Comment by feltnerm** [comment]
I believe they're actively migrating.

> We want to blog about technology, but we are pretty limited on time. Maybe we should spend that time blogging instead of wiring together our own a blogging platform.

For learning and for the hell of it? Why not?! Who says this isn't a potential avenue which could be usable by many?

**Comment by jathey22** [comment]
Hi Guys, yes, we're moving from Compendium to HubSpot for widen.com/blog.

Staying on wordpress for widen.com revamp staring soon (strategy phases
now).

Are you wanting a blog for your Widen work or Fine Uploader?

**Comment by rnicholus** [comment]
I guess I'm not clear on the goal here. I thought it was to blog about
technology, and get Widen's name out in the development community.
Developing our own version of wordpress is probably not a realistic goal,
and if we really just want to get our thoughts out there, nothing we
develop (given our resource and time restrictions) will compare to the
endless array of products that already satisfy all these needs.

**Comment by rnicholus** [comment]
@jathey22 This is not Fine Uploader specific. It would be for the entire Widen development team to participate, per my understanding.

**Comment by jathey22** [comment]
Like! Yeah, we can post anything relevant to marketing technology, content
management, trends, insights and more with connecting marketing content to
the Widen blog (Compendium and then HubSpot later).

If enough participation from dev in areas more technical, it may make sense
to start a new wordpress blog to reach and unite a more technical audience
than the marketing / creative types now.

Chat more?

**Comment by rnicholus** [comment]
Jake - I think the original goal here was to create a developer-specific portal to cater to developer-specific audiences. The site would perhaps contain technical blog entries, info about developer life here, our tech stack and projects, etc. However, we would want to maintain a consistent look, within reason, between this site and the existing widen.com blog. Again, just my thoughts and understanding of the goals here.

**Comment by jathey22** [comment]
Make sense. We could have a developer-specific category under the Widen
blog.

**Comment by feltnerm** [comment]
> I guess I'm not clear on the goal here. I thought it was to blog about technology

That's one goal for sure!

> , and get Widen's name out in the development community.

That's a secondary goal, IMHO. I also feel like that goal adds unnecessary pressure. I think just writing technical stuff down in a communicative way can be good practice to keep your skills sharp, it can help spread more knowledge (both inter- and exter-nally), and it can also open your mind to new ideas on how you could have solved problems.

This idea isn't about me, but part of my ideal goal is that I want everyone here to have ownership of this site, be able to change it at will, be able to collaborate with each other, and be able to easily create and edit content using familiar tools.

Using git, GitHub, Jekyll (the most popular blogging platform -- so I've heard), static HTML, static CSS, and markdown all seemed to check a lot of those boxes. This also opens up an avenue for mentoring for those who'd want to either learn some bits of tech and/or write a post.

> Developing our own version of wordpress is probably not a realistic goal,
and if we really just want to get our thoughts out there, nothing we
develop (given our resource and time restrictions) will compare to the
endless array of products that already satisfy all these needs.

@rnicholus you and I both have dealt with Wordpress for FineUploader. Please tell me you wouldn't let me even try to recreate that behemoth!

Recreating Wordpress is NOT the goal. I hope that's not suggested by my task-list (which is editable, btw). To me, the things I listed above either fall into the category of requirements for *ANY* blog/site or requirements to make it simple enough for people to adopt the tools.

---

Currently, this has been more or less a labor of love, and I'm fine with that. I'm not in any rush. Anyways, this issue has now gotten way off track.

**Comment by feltnerm** [comment]
> If enough participation from dev in areas more technical, it may make sense
to start a new wordpress blog to reach and unite a more technical audience
than the marketing / creative types now.

We don't have any participation yet. I think participation needs to be planted so it can grow.

Also, -1 for Wordpress.

**Comment by glochner** [comment]
I think that if the articles are useful, easy to understand, yet intelligent.  Then the goal of getting Widen's name out in the dev community would naturally follow.  

As long as it's clear that the author holds a title at Widen, I don't think they need to overtly plug Widen technology within the articles.

**Comment by dbeg** [comment]
For anyone interested in what exactly is going on here, @feltnerm and I spun up this idea one afternoon whilst working from 100state. At the time, our main inspiration was an open source portal, similar to http://square.github.io/ or http://netflix.github.io/. This idea transitioned into something more similar to http://githubengineering.com/. We want to see an area where we can share open source projects with the community, which will give Widen a better development presence, but we also want this area to have a platform to explain and expand upon that code. Mark and I envision a place where we can have rich content that highlights our more interesting work. Rolling our own micro-blogging platform seems to be a natural extension of this process in my mind, hence not simply dropping content into a more user-friendly environment.

**Comment by bdotte** [comment]
+1 

Cultivating our development "brand" is hugely desirable for getting the best talent interested in working for us. Being a small company, our name is not widely known, and recruiting can be challenging because of that (hence the involvement in things like MadHacks). A public presence and projects like FineUploader can make a big difference when someone Googles us to see what we're about, FineUploader is often mentioned by developer candidates who have done their homework.

I totally agree this is a worthwhile goal to pursue independent of marketing our software itself.

**Comment by rnicholus** [comment]
Yes, I completely agree that the content of this site is important, and can/should contains things such as:
- developer blogs
- developer events
- info about our open source libraries/projects

My stance is that the content is paramount here, and I'm hoping that development of a micro-blogging platform doesn't get in the way of this.

**Comment by feltnerm** [comment]
Lovin' the discussion!

+1 to what @dbeg said. We're also generating good content based on what we are learning while building this.

> My stance is that the content is paramount here, and I'm hoping that development of a micro-blogging platform doesn't get in the way of this.

Great. Since we are using Jekyll we don't need to write a micro-blogging platform :stuck_out_tongue_winking_eye: 

On a personal note, I'm learning more and more about front-end design by writing custom styles for this thing. That learning is thrown out the window if were to use a platform like wordpress or blogger.

**Comment by thechrisproject** [comment]
Is it worth mentioning that the Netflix Tech Blog runs on Blogger?

**Comment by feltnerm** [comment]
My feeling is that creating this from scratch (i.e., using Jekyll) offers more pros than cons. IMHO, the main reason for using something like hubspot or blogger or wordpress is ease of setup. I just don't see that being important right now since it's not like we have a queue of blog posts. I also think the DIY-ness of this project adds value.

At the end of the day, this is not about me. **I want all of us to own this.** I'm seriously willing to do all those tasks by myself because I believe this is a good idea (as echoed by almost everyone in this thread), but I don't want to do all that in vain.

@dbeg and I thought of this, came up with a plan, and started executing it. This is just our conception of it. We didn't involve everyone up front, even though the intention of the project is to involve everyone eventually. Now that the idea is out in the open (and apparently well received), maybe those who are seriously willing to commit to and are invested in the idea should lay out our goals and discuss them.

**Comment by feltnerm** [comment]
I shuffled the required tasks around a bit after thinking about it more. 

Categories / tags support, Author page, and Software page were all moved into _Nice to Haves_. Seems more appropriate?

/cc @dbeg

**Comment by feltnerm** [comment]
I also moved the `Automation` section into _Nice to Haves_ because that'll be easier to do after documentation is written.

**Comment by rnicholus** [comment]
Just committed a makefile and travis-ci integration. This will allow the site to be automatically published whenever a change is pushed to the develop branch. I'm going to reflect on my solution for a day or so before I test it out, enable it, and move on to something else.

Once this is live, any changes that should _not_ be immediately published must be made to a branch off of develop. Travis will be configured to only look at pushes on the develop branch.

**Comment by feltnerm** [comment]
Woot! Thanks!

**Comment by rnicholus** [comment]
Auto-deploy is up and running. Simply push to develop and travis takes care of the rest. See the [Makefile](https://github.com/Widen/widen.github.io/blob/develop/Makefile) and [travis-ci config](https://github.com/Widen/widen.github.io/blob/develop/.travis.yml) for details.

I included a robots.txt that should be removed or adjusted once you are done with the styling tasks @feltnerm and the site has at least one real post.

**Comment by rnicholus** [comment]
RSS feed is working. Tested it with feedly.

**Comment by rnicholus** [comment]
Created a few new Makefile targets.

To create a new post: `make createPost title="this is my new post"`.

To create a new draft: `make createDraft title="this is my new draft post"`.

**Comment by feltnerm** [comment]
Awesome work, ray. The engineering.widen.com domain works now too, if you
didn't notice already.

**Comment by rnicholus** [comment]
auto-deploy is back up and running

**Comment by jathey22** [comment]
Looking good guys!

Need any help from Danielle or I?

Jake Athey
Marketing Director, Widen
608-443-5472
jathey@widen.com

**Comment by feltnerm** [comment]
We're close!

Just need to review what's there to see if anything is missing before we ship.

Once everything is :+1: all around, to ship, we need to:
- [ ] Turn on `robots.txt`
- [ ] Remove the "First Post"
- [ ] Set the (only) post into `published: true`

**Comment by jathey22** [comment]
Lookin' good fellas!

Jake Athey
Marketing Director, Widen
608-443-5472
jathey@widen.com
