### ISSUE TITLE
Post description (generated or as front matter)

### ISSUE THREAD

**Issue by dbeg** [Widen/widen.github.io#9]

**Comment by feltnerm** [comment]
I think having an optional `excerpt` field in front-matter to display and then falling back to the first 140 or so characters of the post.

**Comment by dbeg** [comment]
This should probably be the next issue addressed. Going to the index with multiple posts seems a little barren without a little more text.

**Comment by feltnerm** [comment]
Good point about the barren index page. What do you think of my proposal above?

**Comment by dbeg** [comment]
Jekyll's built in excerpt variable that is exposed on pages/posts seems to expose headers, which is not really desirable... Trying to find a better way to handle front-matter/generated excerpts while still falling back to generating our own excerpt from the post content ourselves.

@feltnerm @rnicholus thoughts on this one? 40732dcc

**Comment by dbeg** [comment]
[This solution](https://github.com/Widen/widen.github.io/commit/6a6e46cc75fb15a96072de07b534f0da28) seems as good as any...

**Comment by rnicholus** [comment]
Dead link
